from .main_page import MainPageView
from .ccaa_detail import CcaaDetailView
from .market_state import MarketStateView
from .news import NewsView
from .logout import LogoutView
from .overview_map import OverviewMapView
from .placeholder import PlaceholderView
from .profile import ProfileView
from .settings import SettingsView
