import streamlit as st


class NewsView:
    def render(self) -> None:
        news_html = (
            '<div class="main-wrap">'
            '<div class="main-card">'
            '<div class="main-kicker">PharmaTFG Platform</div>'
            '<div class="main-title">News</div>'
            '<div class="main-text">Selección de fuentes clave para validar aprobaciones, alertas y seguir el pulso de la industria.</div>'
            '<div class="news-grid">'
            '<a class="news-card" href="https://www.aemps.gob.es/comunicacion/alertas/medicamentos-uso-humano/" target="_blank">'
            '<div>'
            '<div class="news-card-kicker">Oficial · España</div>'
            '<div class="news-card-title">AEMPS</div>'
            '<div class="news-card-text">Alertas farmacéuticas, notas informativas y problemas de suministro en España.</div>'
            '</div>'
            '<div class="news-card-link">Abrir fuente</div>'
            '</a>'
            '<a class="news-card" href="https://www.ema.europa.eu/en/news-events" target="_blank">'
            '<div>'
            '<div class="news-card-kicker">Oficial · Europa</div>'
            '<div class="news-card-title">EMA</div>'
            '<div class="news-card-text">Novedades regulatorias y comunicados de medicamentos para la UE.</div>'
            '</div>'
            '<div class="news-card-link">Abrir fuente</div>'
            '</a>'
            '<a class="news-card" href="https://www.fda.gov/news-events" target="_blank">'
            '<div>'
            '<div class="news-card-kicker">Oficial · EE. UU.</div>'
            '<div class="news-card-title">FDA News & Events</div>'
            '<div class="news-card-text">Aprobaciones, seguridad y decisiones regulatorias de referencia global.</div>'
            '</div>'
            '<div class="news-card-link">Abrir fuente</div>'
            '</a>'
            '<a class="news-card" href="https://www.fiercepharma.com/" target="_blank">'
            '<div>'
            '<div class="news-card-kicker">Industria · Breaking News</div>'
            '<div class="news-card-title">Fierce Pharma</div>'
            '<div class="news-card-text">Cobertura rápida de compañías, ensayos, fabricación y estrategia pharma.</div>'
            '</div>'
            '<div class="news-card-link">Abrir fuente</div>'
            '</a>'
            '</div>'
            '</div>'
            '</div>'
        )
        st.markdown(news_html, unsafe_allow_html=True)
